# three node cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraMounts:
  - hostPath: /Users/rico/apps/kind/var/local-path-provisioner
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: /Users/rico/apps/kind/var/local-path-provisioner
    containerPath: /var/local-path-provisioner
- role: worker
  extraMounts:
  - hostPath: /Users/rico/apps/kind/var/local-path-provisioner
    containerPath: /var/local-path-provisioner
