apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - mountPath: "/app/data"
      name: my-local-path-claim
  volumes:
  - name: my-local-path-claim
    persistentVolumeClaim:
      claimName: my-local-path-claim
